# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-15 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game_Info_Table',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('home_team', models.CharField(max_length=128)),
                ('away_team', models.CharField(max_length=128)),
                ('stadium', models.CharField(max_length=128)),
                ('date', models.CharField(max_length=16)),
                ('time', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Player_Info_Table',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('number', models.CharField(blank=True, max_length=8)),
                ('position', models.CharField(blank=True, max_length=128)),
                ('hometown', models.CharField(blank=True, max_length=256)),
                ('country', models.CharField(blank=True, max_length=256)),
                ('date_of_birth', models.DateField(blank=True, max_length=16)),
                ('height', models.CharField(blank=True, max_length=8)),
                ('fb', models.CharField(blank=True, max_length=256)),
                ('twitter', models.CharField(blank=True, max_length=256)),
                ('instagram', models.CharField(blank=True, max_length=256)),
                ('snapchat', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Info_Table',
            fields=[
                ('team_name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('date_founded', models.CharField(blank=True, max_length=32)),
                ('city_location', models.CharField(blank=True, max_length=256)),
                ('stadium', models.CharField(blank=True, max_length=256)),
                ('head_coach', models.CharField(blank=True, max_length=256)),
                ('league', models.CharField(max_length=256)),
                ('current_wins', models.CharField(blank=True, max_length=8)),
                ('current_ties', models.CharField(blank=True, max_length=8)),
                ('current_losses', models.CharField(blank=True, max_length=8)),
                ('fb', models.CharField(blank=True, max_length=256)),
                ('twitter', models.CharField(blank=True, max_length=256)),
                ('instagram', models.CharField(blank=True, max_length=256)),
                ('snapchat', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Player_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwsl_app.Player_Info_Table')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwsl_app.Team_Info_Table')),
            ],
        ),
    ]
