# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-17 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player_Info_Table',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('date_of_birth', models.DateField(max_length=8)),
                ('height', models.CharField(max_length=16)),
                ('twitter_link', models.CharField(max_length=512)),
                ('player_club_number', models.IntegerField()),
                ('postition', models.CharField(max_length=256)),
                ('national_team', models.CharField(max_length=256)),
                ('player_national_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team_Info_Table',
            fields=[
                ('team_name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('date_founded', models.DateField(max_length=8)),
                ('city_location', models.CharField(max_length=256)),
                ('stadium', models.CharField(max_length=256)),
                ('general_manager', models.CharField(max_length=256)),
                ('league', models.CharField(max_length=256)),
                ('current_wins', models.IntegerField()),
                ('current_ties', models.IntegerField()),
                ('current_losses', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='player_info_table',
            name='current_club_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwsl_app.Team_Info_Table'),
        ),
    ]
