# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-15 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwsl_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_info_table',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
