# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-23 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwsl_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_Info_Table',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('home_team', models.CharField(max_length=128)),
                ('away_team', models.CharField(max_length=128)),
                ('stadium', models.CharField(max_length=128)),
                ('date', models.DateField(max_length=16)),
                ('time', models.DateTimeField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='player_info_table',
            name='player_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
