# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-23 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwsl_app', '0002_auto_20191023_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_info_table',
            name='hometown',
            field=models.CharField(default='Unknown', max_length=256),
            preserve_default=False,
        ),
    ]
